# Generated by Django 5.1.4 on 2025-01-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previous_work',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.CharField(max_length=2000),
        ),
    ]
